### PR TITLE
Make nightly builds more accessible

### PR DESCRIPTION
**Pull request by dizzzz**
a simple python script to generate a HTML page for the nightly builds. The result:

exist-db_nightly_builds

### CODE REVIEW

**Comment by joewiz** [comment]
Beautiful!

**Comment by dizzzz** [comment]
i found it rather difficult to pick the most recent build..... that its gone now..

**Comment by joewiz** [comment]
Agreed, I had the same problem with the old display.

**Comment by adamretter** [comment]
@dizzzz Excellent work! Thank you very much :-)

**Comment by joewiz** [comment]
Looks great! http://static.adamretter.org.uk/exist-nightly/

**Comment by dizzzz** [comment]
:)

**Pull request merged**
